# Generated by Django 5.2.3 on 2025-06-25 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='Organization',
            new_name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'organization')},
        ),
    ]
